function [pulsar] = find_psr(PSR_NAME)
load('millisecond_pulsar_database.mat');
for i = 1:length(NAME)
    if(strcmp(PSR_NAME,NAME(i)))
        break;
    elseif(strcmp(PSR_NAME,JNAME(i)))
        break;
    end
    if(i == length(NAME))
       error('Pulsar name not found');
    
    end
end
pulsar = struct('Name', NAME(i), 'JName', JNAME(i), 'A1', A1(i), 'A1_err', A1err(i), ...
    'Age', AGE(i), 'Age_i', AGE_I(i), 'Assoc', ASSOC(i), 'B_LC', B_LC(i), 'Binary', BINARY(i), ...
    'BinComp', BINCOMP(i), 'BSurf', BSURF(i), 'BSurf_i', BSURF_I(i), 'DecJ', DECJ(i), ...
    'DecJ_err', DECJerr(i), 'DecJD', DECJD(i), 'Disc', DISC(i), 'Dist', DIST(i), ...
    'Dist_DM', DIST_DM(i), 'DM', DM(i), 'DM_err', DMerr(i), 'DM1', DM1(i), 'DM1_err', DM1err(i), ...
    'DMsinb', DMsinb(i), 'ECC', ECC(i), 'ECC_err', ECCerr(i), 'Edot', EDOT(i), 'Edotd2', EDOTD2(i), ...
    'ELat', ELAT(i), 'ELat_err', ELATerr(i), 'ELong', ELONG(i), ...
    'ELong_err', ELONGerr(i), 'EPS1', EPS1(i), 'EPS1_err', EPS1err(i), 'EPS2', EPS2(i), ...
    'EPS2_err', EPS2err(i), 'F0', F0(i), 'F0_err', F0err(i), 'F1', F1(i), 'F1_err', F1err(i), ...
    'F2', F2(i), 'F2_err', F2err(i), 'F3', F3(i), 'F3_err', F3err(i), 'GB', Gb(i), 'GL', Gl(i), ...
    'Median', Median(i), 'Minimum', Minimum(i), 'NGLT', NGLT(i), 'OM', OM(i), 'OM_err', OMerr(i), ...
    'OSurvey', OSURVEY(i), 'P0', P0(i), 'P0_err', P0err(i), 'P1', P1(i), ...
    'P1_err', P1err(i), 'P1_i', P1_I(i), 'PB', PB(i), 'PB_err', PBerr(i), 'PEpoch', PEPOCH(i), ...
    'PMDec', PMDEC(i), 'PMDec_err', PMDECerr(i), 'PMElat', PMELAT(i), 'PMElat_err', PMELATerr(i), ...
    'PMElong', PMELONG(i), 'PMElong_err', PMELONGerr(i), 'PMRA', PMRA(i), 'PMRA_err', PMRAerr(i), ...
    'PMTot', PMTOT(i), 'PMTot_err', PMTOTerr(i), 'PosEpoch', POSEPOCH(i), 'PSR', PSR(i), ...
    'PX', PX(i), 'PX_err', PXerr(i), 'R_Lum', R_LUM(i), 'R_Lum14', R_LUM14(i), 'RAJ', RAJ(i), ...
    'RAJ_err', RAJerr(i), 'RAJD', RAJD(i), 'RM', RM(i), 'RM_err', RMerr(i), 'S400', S400(i), ...
    'S400_err', S400err(i), 'S1400', S1400(i), 'S1400_err', S1400err(i), 'S2000', S2000(i), ...
    'S2000_err', S2000err(i), 'Survey', SURVEY(i), 'T0', T0(i), 'T0_err', T0err(i), 'TASC', TASC(i), ...
    'TASC_err', TASCerr(i), 'Tau_sc', TAU_SC(i), 'Tau_sc_err', TAU_SCerr(i), 'Units', UNITS(i), ...
    'VTrans', VTRANS(i), 'W10', W10(i), 'W10_err', W10err(i), 'W50', W50(i), 'W50_err', W50err(i), ...
    'XX', XX(i), 'YY', YY(i), 'ZZ', ZZ(i));
end
